name: Compile examples folder

on:
  - push
  - pull_request

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: arduino/compile-sketches@v1
          with:
            libraries: |
              - source-path: ./
