name: Compile Examples

on:
  - push
  - pull_request

jobs:
  compile-examples:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      
      matrix:
        board:
          - fqbn: arduino:avr:uno
          - fqbn: arduino:avr:nano
    
    steps:
        - uses: actions/checkout@v6
        - uses: arduino/compile-sketches@v1
          with:
            fqbn: ${{ matrix.board.fqbn }}
            libraries: |
              - source-path: .
